### ISSUE TITLE
Change MoTrPAC logo in the search engine to the one used on the MoTrPAC DCC page

### ISSUE THREAD

**Issue by AviMaayan** [MaayanLab/DRC-Portal-Issues#1]
<img width="981" alt="Screen Shot 2024-02-14 at 4 00 14 PM" src="https://github.com/MaayanLab/DRC-Portal-Issues/assets/12749033/0cc9557b-f199-4f37-adde-482a9de9b622">

**Comment by u8sand** [comment]
This comes straight from the database entry for the DCC, also not seeing the difference
![image](https://github.com/MaayanLab/DRC-Portal-Issues/assets/1341861/e6d8a0af-b768-45ed-93ea-e360d4877ce9)

**Comment by AviMaayan** [comment]
I think this is their correct logo... but I will ask them.
![MoTrPAC](https://github.com/MaayanLab/DRC-Portal-Issues/assets/12749033/431e2206-9fe5-4a2f-ab8d-bace39d0db25)

**Comment by AviMaayan** [comment]
We were using the right logo... my bad.
