### ISSUE TITLE
Add MoTrPAC Office Hours to the Outreach page

### ISSUE THREAD

**Issue by jimmyzhen** [MaayanLab/DRC-Portal-Issues#2]
Please add MoTrPAC DCC's monthly office hour to the [Outreach page](https://info.cfde.cloud/info/outreach).

Description:
> The MoTrPAC Bioinformatics Center (BIC) hosts monthly open office hours to support the scientific community. Each session is hosted by one member from our infrastructure team and one from our bioinformatics team with a focus on the discussions of MoTrPAC data.

Visit Event Page link:
> https://motrpac-data.org

**Comment by jeevangelista** [comment]
added

**Comment by jeevangelista** [comment]
let me know if you want to update the image that I used

**Comment by jimmyzhen** [comment]
@jeevangelista Thank you for the quick turnaround! The correct MoTrPAC logo image should be the same as seen on this page: https://data.cfde.cloud/data/matrix

**Comment by jeevangelista** [comment]
@jimmyzhen updated
