### ISSUE TITLE
Main logo doesn’t redirect to main page

### ISSUE THREAD

**Issue by heesukim628** [MaayanLab/DRC-Portal-Issues#25]
Clicking the main logo can take users to the landing page of either the info/data portal. 

![image](https://github.com/MaayanLab/DRC-Portal-Issues/assets/118917155/bc04db68-b938-4ae5-8886-168b6254af4b)

**Comment by jeevangelista** [comment]
One question, if I'm on the data portal, should this be pointing to the info portal?

**Comment by AviMaayan** [comment]
I think it would be better to go to the data portal home page if you are on the data portal.
