### ISSUE TITLE
Move KC webinar from 4/26 to past events

### ISSUE THREAD

**Issue by AviMaayan** [MaayanLab/DRC-Portal-Issues#26]

**Comment by heesukim628** [comment]
There are following webinars from the series. 
![image](https://github.com/MaayanLab/DRC-Portal-Issues/assets/118917155/1861ab23-ac29-49b5-809f-bec3325ada11)

can we make webinars in the series have individual cards? /or add an end date of 12/20 on this card?

**Comment by AviMaayan** [comment]
We should have a card for each webinar since there aren't that many CFDE events yet.
