### ISSUE TITLE
Login issues using email

### ISSUE THREAD

**Issue by ReneRanzinger** [MaayanLab/DRC-Portal-Issues#30]
I got some email regarding assets pending review. I used the link in the email and ended up on login page:

![email](https://github.com/MaayanLab/DRC-Portal-Issues/assets/2267640/3d844588-dacf-48d5-8d2a-d7554fbba983)

I used the "or email" option (mainly because I am not sure if the other IDs are linked). After entering my email this screen is shown: 

![request](https://github.com/MaayanLab/DRC-Portal-Issues/assets/2267640/bb95b1c9-f6dd-452f-b45a-434cf6440e54)

Around 4 minutes later the announced email arrives. But by click on the link in the mail I end up here:

![error](https://github.com/MaayanLab/DRC-Portal-Issues/assets/2267640/29c64688-2343-4804-b85c-b01780b2ced3)

The sign in link in the dialog brings me back to the login page. I tried this multiple times over the last few days.

**OS:** 
* Windows 10
* Manjaro 23.1 (Plasma)

**Browser:**
* Firefox 125.0.3

**Comment by AviMaayan** [comment]
Hi @ReneRanzinger We will look into why this happens. The delay is likely happening after the e-mail is sent. In the meantime, you can try logging in using the other options. I believe your ORCID should work but need to check with @stephanieolaiya.

**Comment by AviMaayan** [comment]
Hi @stephanieolaiya if this issue is resolved, please close it with a comment of what was done.

**Comment by stephanieolaiya** [comment]
Added HEAD check to temporarily fix as done [here](https://next-auth.js.org/tutorials/avoid-corporate-link-checking-email-provider). Issue will be resolved with KeyCloak implementation.
