### ISSUE TITLE
Clicking on event tag filters cards, but doesn't update UI with "checkbox"

### ISSUE THREAD

**Issue by seandavi** [MaayanLab/DRC-Portal-Issues#32]
https://info.cfde.cloud/training_and_outreach

Observed behavior after clicking on "fellowship":
![image](https://github.com/MaayanLab/DRC-Portal-Issues/assets/92435/945041d2-bbc2-40cf-a1f0-8a0f80578876)

Expected behavior:
- Checkbox on left side beside "fellowship" to be filled.

super-minor issue for an otherwise fantastic resource!

**Comment by jeevangelista** [comment]
should be fixed
