### ISSUE TITLE
Gene Set Library name for MoTrPAC

### ISSUE THREAD

**Issue by jimmyzhen** [MaayanLab/DRC-Portal-Issues#4]
What does "Sigs 2023" refer to in the "MoTrPAC Rat Exercise Sigs 2023" MoTrPAC Gene Set Library name?

**Comment by AviMaayan** [comment]
Hi @jimmyzhen we created a gene set library from the published rat study. The gene sets in this library are up/down genes before and after exercise at different time points in different tissues. For example, "T59-Kidney Male 2W Up". Any comments on how to do this better, and whether we can add new libraries from the new data that will be published soon would be great.

**Comment by jimmyzhen** [comment]
Hi @AviMaayan, thank you for the clarification. The MoTrPAC study data currently available to the public is pertinent to the young adult rats performing endurance training exercise. If the gene sets are derived from this study, then I think "MoTrPAC Endurance Trained Young Adult Rats" may be a bit more indicative than "MoTrPAC Rat Exercise Sigs 2023" as the library name. Please feel free to keep it as is if you have specific reasons to retain "Sigs 2023".

**Comment by AviMaayan** [comment]
Hi @jimmyzhen there is some limit on the size of the name and we use the year for noting the release date in case we want to update it later, how about: "MoTrPAC Endurance Trained Rats 2023"?

**Comment by jimmyzhen** [comment]
Hi @AviMaayan, that sounds great! Thank you!
