### ISSUE TITLE
MoTrPAC Gene Set data source

### ISSUE THREAD

**Issue by jimmyzhen** [MaayanLab/DRC-Portal-Issues#5]
Would you mind letting us know where the MoTrPAC Gene Set data (e.g. https://data.cfde.cloud/data/processed/gene_set/03e270e2-7b69-584c-a30b-d7ed8fb2a5ba) derived from? Thank you.

**Comment by AviMaayan** [comment]
The gene sets were derived from the *timewise*.txt and *training*txt files downloaded from the MoTrPAC data portal. Each gene set represents a specific tissue, sex, and timepoint. Only the genes with <0.05 adj pval were retained. Up and down genes were selected based on their logFC. Form the *training*txt the tissue metadata. The genes that changed over the training time course using likelihood ration test were retained. Each set in the library represents a tissue, filtered by adj pval and named the consensus gene set for the tissue.

**Comment by jimmyzhen** [comment]
Got it. @AviMaayan, thank you for the clarification!
