### ISSUE TITLE
Dead link to CFDE-GSE from CFDE portal

### ISSUE THREAD

**Issue by AviMaayan** [MaayanLab/DRC-Portal-Issues#62]
<img width="682" alt="Screenshot 2024-09-07 at 8 05 48 PM" src="https://github.com/user-attachments/assets/1c14b08f-781c-4c26-9fe0-1b514df4fa2b">

**Comment by u8sand** [comment]
Guessing it should be updated to https://gse.cfde.cloud/ ?

**Comment by AviMaayan** [comment]
Yes...

**Comment by u8sand** [comment]
Well I updated it in the database for now, @jeevangelista should update the table on S3 so that a re-ingest will retain the change
