### ISSUE TITLE
Change G2SG to GeneSetCart

### ISSUE THREAD

**Issue by AviMaayan** [MaayanLab/DRC-Portal-Issues#67]
<img width="582" alt="Screenshot 2024-09-23 at 1 54 33 PM" src="https://github.com/user-attachments/assets/251d09ab-4ccf-48b8-9c6b-9282f6b5d0d8">

**Comment by heesukim628** [comment]
Updated the name and description on the spreadsheet. Will we update the domain as well?

**Comment by AviMaayan** [comment]
Please coordinate with Giacomo. He should be back tomorrow.

**Comment by heesukim628** [comment]
Per Giacomo: I think Avi had said the URL is fine, though it can be changed if needed.
