### ISSUE TITLE
CFDE portal: Twitter widget not working

### ISSUE THREAD

**Issue by ReneRanzinger** [MaayanLab/DRC-Portal-Issues#8]
<img width="735" alt="Screenshot 2024-03-19 at 1 50 46 PM" src="https://github.com/MaayanLab/DRC-Portal-Issues/assets/2267640/76b86cc2-9b4b-45e7-8378-a5dde1e7d9c2">

Known issue. The twitter feed is only visible if you are logged in to twitter. If not or if you work in an anonymous browser window it shows that you have no tweets.

**Comment by jeevangelista** [comment]
regarding this, this is a known bug for twitter. should we just remove this section? https://devcommunity.x.com/t/again-list-widget-says-nothing-to-see-here-yet-if-logged-out/198782/395?page=13

**Comment by AviMaayan** [comment]
Is there a way to show it and hide it based on whether the user is logged in? We don't want to lose it completely...

**Comment by u8sand** [comment]
I looked into this but frankly their free API seems completely unusable.
- I couldn't figure out a way to detect if the user is logged in or not
- I wasn't able to use the free API to list tweets by a user for rendering them ourselves without the twitter embed

I was however able to test out https://github.com/d60/twikit and that could work, though it's python, slow, and likely not going to work forever if Elon is serious about preventing non-api use

**Comment by ReneRanzinger** [comment]
For GlyGen we double post on X and Mastodon, and we use a Mastodon widget for the home page. Its not a pure react widget but it works independent if you are logged in to Mastodon or not.
